Remove "filthy magic stack backtracking" in favor of BASE_DIR
joke2k/django-environ pull request #252
Opened 2020-03-19 08:00 UTC by nickcannariato

The `read_env` documentation currently states:

> If not given a path to a dotenv path, does filthy magic stack backtracking to find manage.py and then find the dotenv.

Based on joke2k/django-environ#88, it appears that this behavior is rather fragile.

To improve this, I think the package should document that read_env expects you to provide a path. If one is not provided, it will attempt to use the BASE_DIR constant from the django settings module. If an ImportError is encountered while it attempts to do this, read_env will assume there's no .env file to be found, log an info message to that effect, and continue on.

fixes: joke2k/django-environ#88

2021-09-04 14:15 UTC, sergeyklay commented
PR was closed by mistake. Reopened it.

2021-09-06 08:13 UTC, sergeyklay approved these changes

2021-09-06 08:19 UTC, sergeyklay requested changes
There are some linting issues. Could you please take a look

2021-09-06 08:19 UTC, sergeyklay commented on environ/environ.py
>  import sys
'sys' imported but unused

2021-09-06 08:19 UTC, sergeyklay commented on environ/environ.py
> +from urllib.parse import ParseResult, parse_qs, unquote_plus, urlparse, urlunparse
Imported names are in the wrong order
```suggestion
from urllib.parse import parse_qs, ParseResult, unquote_plus, urlparse, urlunparse
```

2021-09-06 08:19 UTC, sergeyklay commented on environ/environ.py
> +from urllib.parse import ParseResult, parse_qs, unquote_plus, urlparse, urlunparse
Also this line too long (82 > 79 characters)

2021-09-06 08:19 UTC, sergeyklay commented on environ/environ.py
> +from .compat import DJANGO_POSTGRES, REDIS_DRIVER, ImproperlyConfigured, json
Imported names are in the wrong order

```suggestion
from .compat import DJANGO_POSTGRES, ImproperlyConfigured, json, REDIS_DRIVER
```

2021-09-06 08:19 UTC, sergeyklay commented on environ/environ.py
> +        environ.environ.ImproperlyConfigured: Create required path: /home/not_existing_dir
E501 line too long (90 > 79 characters)

2021-09-06 08:19 UTC, sergeyklay commented on environ/environ.py
> +        >>> assets, scripts = public.path('assets'), public.path('assets', 'scripts')
line too long (85 > 79 characters)

2021-09-06 08:19 UTC, sergeyklay commented on environ/environ.py
> +        (<Path:/home/public/assets/styles>, '/home/public/assets/styles', <Path:/home/public>)
line too long (94 > 79 characters)

2021-09-06 08:20 UTC, sergeyklay commented on environ/environ.py
> +            except (ImportError, NameError):
What about AttributeError?

2022-04-13 05:00 UTC, jayvdb commented
@sergeyklay is it possible to change the merge target of this PR to be `main` ?

2022-06-13 20:14 UTC, sergeyklay commented
@jayvdb Usually we merge changes to the `develop` branch. Then, before the release, we merge the `develop` branch into the `main` and make a release from the `main` branch.

2022-06-13 23:07 UTC, jayvdb commented
No worries. At the time I wrote that, there was no `develop` branch.

2026-04-21 00:24 UTC, joke2k commented
Thanks for the proposal. We are closing this PR because the suggested fallback direction is not safe for django-environ. In the common Django setup, Env.read_env() is called from settings.py during Django bootstrap, so relying on django.conf.settings (or importing the module pointed to by DJANGO_SETTINGS_MODULE to read BASE_DIR) can re-enter a partially initialized settings module and create fragile import-order behavior.

We also do not need that fallback to address the documentation concern here. The supported parameters and their behavior are already documented, and the recommended pattern for Django projects is to pass the .env path explicitly, for example via BASE_DIR('.env') or an equivalent explicit path.

Given that this PR is tied to an unsafe fallback approach and the documentation side is already covered, we are closing it.

2026-04-21 00:24 UTC, closed without merging