Add docker-style file variable support (fixes #189)
joke2k/django-environ pull request #328
Opened 2021-09-13 01:55 UTC by SmileyChris

2021-09-13 11:23 UTC, sergeyklay commented
I'll take a look ASAP

2021-09-13 13:30 UTC, SmileyChris commented
Oh, we're supporting 3.5 still. Easy changes to make for that.
Windows CI fails because it can't read temp files 😒

2021-09-13 13:33 UTC, SmileyChris commented
One design decision that should be considered: currently if you use a `_FILE` key on a missing file (or not enough permissions), then it will fail hard with an os exception -- the thinking being that failing loud is better than silently if you explicitly asked to use a file.

2021-09-13 18:37 UTC, sergeyklay commented
@SmileyChris Could you please update the PR descrption by adding a bit more info about purpose and possible use cases.

2021-09-13 21:46 UTC, SmileyChris commented
@sergeyklay updated description, pushed py3.5 fix, 100% coverage, and hopefully fixed windows ci tests too

2021-09-14 21:26 UTC, SmileyChris commented
Lint fixed (pfft, should use black's 88 line length now :D)

2021-09-14 23:07 UTC, sergeyklay requested changes
In general, everything looks quite good, except for a few nitpicking from me.

2021-09-14 23:31 UTC, SmileyChris commented on README.rst
> +    SECRET_KEY = env('SECRET_KEY')
Keeping it simple is good, but then I don't think anyone will find the feature if it lives there... Could I trim it down instead?

2021-09-15 00:10 UTC, SmileyChris commented on README.rst
> +    SECRET_KEY = env('SECRET_KEY')
Ok, removed it (but added a short mention of how to do it in the "Features" bullet point that remains in README)

2021-09-15 00:10 UTC, SmileyChris commented on environ/environ.py
> +    ENVIRON = FileAwareMapping()
Done

2021-09-15 07:52 UTC, sergeyklay approved these changes

2021-09-15 07:53 UTC, merged

2021-09-15 07:53 UTC, sergeyklay commented
Merged! Thank you for the patch, and for helping us make django-environ better.

2021-09-22 06:11 UTC, panteparak commented
is there a timeline for the next release that includes this PR?

2021-09-22 06:39 UTC, sergeyklay commented
I'll try to find time for release this weekend.