Add interpolate option
joke2k/django-environ pull request #419
Opened 2022-09-26 13:23 UTC by David-Wobrock

The argument is already documented but not implemented yet.
Fixes #415

2022-12-17 10:35 UTC, David-Wobrock commented
Hey @WTK 

Thanks for the comment, I think it would be worth creating another PR to fix the issue you are mentioning.
The hereby PR is adding the logic to deactivate the `interpolate` option, whereas, from what I'm understanding, you are mentioning that interpolation doesn't work properly.

2023-07-10 15:24 UTC, ThalusA commented
@sergeyklay I see you are now the main contributor with push access to this repository, would you mind merging this simple PR ? It just makes interpolate works like it is supposed to be. It doesn't create new errors or anything like that.

2023-07-10 16:11 UTC, David-Wobrock commented
Rebased to fix the conflict.

2023-07-10 20:14 UTC, ThalusA approved these changes

2023-07-14 08:37 UTC, sergeyklay requested changes
@David-Wobrock I've been looking through your pull request and in principle, everything looks good. However, there seem to be a few builds that failed, notably the code style checks and linters. Could you please make the necessary adjustments? It would greatly assist in maintaining our codebase's quality and readability. Also, I would appreciate it if you could add an entry in the changelog about these changes as well as update corresponding article https://github.com/joke2k/django-environ/blob/main/docs/tips.rst#proxy-value. This would save me some time and ensure that we keep our documentation up to date.

2023-07-14 08:37 UTC, sergeyklay commented on environ/environ.py
> +        if self.interpolate and isinstance(value, (bytes, str)) and var_name not in NOT_EXPANDED:
line too long (97 > 79 characters)

2023-07-14 14:37 UTC, David-Wobrock commented
Hi @sergeyklay 

Thanks for your input 👍 

> However, there seem to be a few builds that failed

I adapted the code ✔️ We should be good now (linting passes locally).
I forced-push, to keep one lean commit, but it seems that the PR requires new approval for running the CI 😕 

> add an entry in the changelog about these changes

Done ✔️ 

> update corresponding article https://github.com/joke2k/django-environ/blob/main/docs/tips.rst#proxy-value

From my understanding, everything is already documented in the tips section.
That was one of the major reasons of the PR: the logic was documented, but not implemented 😄

2023-07-14 17:20 UTC, ThalusA approved these changes

2023-07-17 15:22 UTC, sergeyklay approved these changes

2023-07-17 15:22 UTC, merged

2023-07-17 15:22 UTC, sergeyklay commented
Thank you!

2023-08-30 20:41 UTC, sergeyklay commented
@David-Wobrock Thank you for your contribution to the project. Unfortunately, after implementing your interpolation solution, [we've encountered issues from our users](https://github.com/joke2k/django-environ/issues/485). Due to this, we've decided to revert your changes and release a patch version.

This is not a reflection on the quality of your code or idea; it's just that it has caused some complications in this particular context.