handle inline comments, and ignore spaces outside quotes
joke2k/django-environ pull request #475
Opened 2023-05-30 15:49 UTC by lvanderree

capable of handling inline comments (outside quotes).

So if you want "#" hashes in your values, place them inside quotes.

Also ignoring spaces outside quotes

2023-05-30 15:53 UTC, lvanderree commented
I noticed issues regarding this PR:

- https://github.com/joke2k/django-environ/issues/91
- https://github.com/joke2k/django-environ/pull/475

2023-07-06 10:20 UTC, sergeyklay requested changes
Great work on the PR! Noticed some linter warnings. Please, could you address them? After that, it'll be ready for merge. Thanks!

2023-07-06 10:20 UTC, sergeyklay commented on CHANGELOG.rst
> +- Added capability to handle comments after #, after quoted values, like `KEY= 'value_1 # value_2' # comment`
```suggestion
- Added capability to handle comments after #, after quoted values, like ``KEY= 'value_1 # value_2' # comment``
```

2023-07-06 10:20 UTC, sergeyklay commented on environ/environ.py
> +                # search for value within quotes, ignore comments after # (outside quotes)
I paraphrased and reformatted your comment a bit to make it clearer and satisfy the code style.

```suggestion
                # Look for value in quotes, ignore post-# comments
                # (outside quotes)
```

2023-07-06 10:20 UTC, sergeyklay commented on environ/environ.py
> +                    # if no quotes, search for value, ignore comments after first #
I paraphrased and reformatted your comment a bit to make it clearer and satisfy the code style.

```suggestion
                    # For no quotes, find value, ignore comments
                    # after the first #
```

2023-07-06 10:20 UTC, sergeyklay commented on tests/test_env.py
> +        #                       ) # TODO: fix this
Do we really need this piece of code?

2023-07-06 21:15 UTC, sergeyklay approved these changes

2023-07-06 21:16 UTC, sergeyklay commented
Looks great. Thank you for contributing and patience

2023-07-06 21:17 UTC, merged

2023-09-06 18:35 UTC, jonnyhsu commented
> So if you want "#" hashes in your values, place them inside quotes.

Unfortunately the Django `SECRET_KEY` has "#" as a valid character, so this is actually a fairly serious breaking change.

2023-09-08 14:46 UTC, lvanderree commented
> Unfortunately the Django `SECRET_KEY` has "#" as a valid character, so this is actually a fairly serious breaking change.

what is the breaking change exactly? Have you got an example that isn't working anymore?
As far as a I see everything is still possible, but with the additional functionality to also be able to place comments

2023-09-08 16:13 UTC, sergeyklay commented
.env file contents:
```
SECRET_KEY_499_1=abc#def
SECRET_KEY_499_2='abc#def'
SECRET_KEY_499_3='abc\#def'
SECRET_KEY_499_4="abc\#def"
SECRET_KEY_499_5=abc\#def
```

Test 2750dd54e0e4b1b591a31409cfb1dc16a82b958d (this PR)
```
SECRET_KEY_499_1=abc
SECRET_KEY_499_2=abc#def
SECRET_KEY_499_3=abc\#def
SECRET_KEY_499_4="abc\
SECRET_KEY_499_5=abc\
```

Test 8874288ac11bc70fa491439d52a4c307f9388aea (v0.10.0)
```
SECRET_KEY_499_1=abc#def
SECRET_KEY_499_2=abc#def
SECRET_KEY_499_3=abc\#def
SECRET_KEY_499_4=abc#def
SECRET_KEY_499_5=abc\#def
```

2023-09-09 10:49 UTC, sergeyklay commented
Hey @lvanderree,

I'm currently working on some modifications to the functionality you introduced in this PR. While the inline comments feature is useful, it has led to some unintended side effects that need addressing. I've opened a new pull request (see [#500](https://github.com/joke2k/django-environ/pull/500)) to tackle these issues.

I'd appreciate your thoughts and any feedback you might have on this.

2023-09-15 17:59 UTC, jonnyhsu commented
> > Unfortunately the Django `SECRET_KEY` has "#" as a valid character, so this is actually a fairly serious breaking change.
> 
> what is the breaking change exactly? Have you got an example that isn't working anymore? As far as a I see everything is still possible, but with the additional functionality to also be able to place comments

If the SECRET_KEY variable starts with a # then the site will not load, because a non-blank secret key is required. If the SECRET_KEY contains a #, then the key will be silently shortened which reduces security.

2023-09-20 20:59 UTC, sergeyklay commented on tests/test_env.txt
> +STR_QUOTED_INCLUDE_HASH='foo # with hash' # not comment
See https://github.com/joke2k/django-environ/pull/500